[warning-fix][-Wimplicit-*]
Fix warnings such as
-- warning: type defaults to ‘int’ in declaration of ‘old_curpos’ [-Wimplicit-int]
-- warning: implicit declaration of function ‘STMTlist_out’ [-Wimplicit-function-declaration]

Also fix fedex_plus/selects.c:574:8: error: too few arguments to function ‘FundamentalType’,
a bug uncovered by fixing the implicit declaration warning. Assumed that the second argument
should be 0, like most other calls to the function.